// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0hisfDHOosNBDrs52JcWwEtDK33XtQ8A',
    appId: '1:22763211919:web:39ea527a0acea27022f4fa',
    messagingSenderId: '22763211919',
    projectId: 'todo-ba892',
    authDomain: 'todo-ba892.firebaseapp.com',
    storageBucket: 'todo-ba892.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHwVylQD_qPn9s4HXtXV9DmiYgvG77lxs',
    appId: '1:22763211919:android:3c1abd4754242bb422f4fa',
    messagingSenderId: '22763211919',
    projectId: 'todo-ba892',
    storageBucket: 'todo-ba892.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0hisfDHOosNBDrs52JcWwEtDK33XtQ8A',
    appId: '1:22763211919:web:a1b03b71aecda38422f4fa',
    messagingSenderId: '22763211919',
    projectId: 'todo-ba892',
    authDomain: 'todo-ba892.firebaseapp.com',
    storageBucket: 'todo-ba892.appspot.com',
  );
}
